apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-templates-api-gateway
  namespace: shadowchats
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  api-gateway-appsettings.json.tpl: |
    {
      "Kubernetes": {
        "Namespace": "shadowchats",
        "ServiceNames": [
          "authentication"
        ]
      },
      "JwtSettings": {
        "SecretKeyBase64": "{{ with secret "secret/api-gateway" }}{{ .Data.data.jwt_secret }}{{ end }}",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "ReverseProxy": {
        "Routes": [
          {
            "RouteId": "authentication-routes",
            "ClusterId": "authentication",
            "Match": {
              "Path": "/authentication/{**catch-all}"
            },
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "PathRemovePrefix": "/authentication",
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          }
        ],
        "Clusters": [
          {
            "ClusterId": "authentication",
            "LoadBalancingPolicy": "LeastRequests",
            "HealthCheck": {
              "Active": {
                "Enabled": true,
                "Interval": "00:00:10",
                "Timeout": "00:00:05",
                "Policy": "ConsecutiveFailures",
                "FailureThreshold": 2,
                "Path": "/ready"
              },
              "Passive": {
                "Enabled": true,
                "Policy": "TransportFailureRate",
                "ReactivationPeriod": "00:02:00"
              }
            },
            "HttpRequest": {
              "Version": "2",
              "VersionPolicy": "RequestVersionExact",
              "AllowResponseBuffering": false,
              "RequestTimeout": "00:00:30"
            }
          }
        ]
      }
    }
