apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-templates-api-gateway
  namespace: shadowchats
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  api-gateway-appsettings.json.tpl: |
    {
      "Kubernetes": {
        "Namespace": "shadowchats",
        "ServiceNames": [
          "authentication"
        ]
      },
      "JwtSettings": {
        "SecretKeyBase64": "{{ with secret "secret/api-gateway" }}{{ .Data.data.jwt_secret }}{{ end }}",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "ReverseProxy": {
        "Routes": [
          {
            "RouteId": "authentication-route-http1",
            "ClusterId": "authentication-http1",
            "Match": {
              "Hosts": [ "shadowchats.api.gateway1.local" ],
              "Path": "/{path:regex(^authentication\\.[a-zA-Z_][\\w]*/[A-Z][A-Za-z0-9_]*$)}"
            },
            "Order": 2,
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          },
          {
            "RouteId": "authentication-route-http2",
            "ClusterId": "authentication-http2",
            "Match": {
              "Hosts": [ "shadowchats.api.gateway2.local" ],
              "Path": "/{path:regex(^authentication\\.[a-zA-Z_][\\w]*/[A-Z][A-Za-z0-9_]*$)}"
            },
            "Order": 2,
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          },
          {
            "RouteId": "authentication-route-unsafe-http1",
            "ClusterId": "authentication-http1",
            "Match": {
              "Hosts": [ "shadowchats.api.gateway1.local" ],
              "Path": "/{path:regex(^authentication\\.[a-zA-Z_][\\w]*/[A-Z][A-Za-z0-9_]*$)}"
            },
            "Order": 1
          },
          {
            "RouteId": "authentication-route-unsafe-http2",
            "ClusterId": "authentication-http2",
            "Match": {
              "Hosts": [ "shadowchats.api.gateway2.local" ],
              "Path": "/{path:regex(^authentication\\.[a-zA-Z_][\\w]*/[A-Z][A-Za-z0-9_]*$)}"
            },
            "Order": 1
          }
        ],
        "Clusters": [
          {
            "ClusterId": "authentication-http1",
            "LoadBalancingPolicy" : "LeastRequests",
            "HealthCheck": {
              "Active": {
                "Enabled": "true",
                "Interval": "00:00:10",
                "Timeout": "00:00:10",
                "Policy": "ConsecutiveFailures",
                "Path": "/ready"
              },
              "Passive": {
                "Enabled": true,
                "Policy" : "TransportFailureRate",
                "ReactivationPeriod" : "00:00:10"
              }
            }
          },
          {
            "ClusterId": "authentication-http2",
            "LoadBalancingPolicy" : "LeastRequests",
            "HealthCheck": {
              "Active": {
                "Enabled": "true",
                "Interval": "00:00:10",
                "Timeout": "00:00:10",
                "Policy": "ConsecutiveFailures",
                "Path": "/ready"
              },
              "Passive": {
                "Enabled": true,
                "Policy" : "TransportFailureRate",
                "ReactivationPeriod" : "00:00:10"
              }
            }
          }
        ]
      }
    }
