apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-templates-api-gateway
  namespace: shadowchats
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  api-gateway-appsettings.json.tpl: |
    {
      "Kubernetes": {
        "Namespace": "shadowchats",
        "ServiceNames": [
          "authentication"
        ]
      },
      "JwtSettings": {
        "SecretKeyBase64": "{{ with secret "secret/api-gateway" }}{{ .Data.data.jwt_secret }}{{ end }}",
        "Issuer": "Shadowchats",
        "Audience": "ShadowchatsUsers"
      },
      "ReverseProxy": {
        "Routes": [
          {
            "RouteId": "authentication-route",
            "ClusterId": "authentication",
            "Match": {
              "Hosts": [ "shadowchats.authentication.local" ]
              "Path": "/{**catch-all}"
            },
            "AuthorizationPolicy": "AccountPolicy",
            "Transforms": [
              {
                "RequestHeader": "X-Account-Id",
                "Set": "{Sub}"
              }
            ]
          },
          {
            "RouteId": "authentication-route-unsafe",
            "ClusterId": "authentication",
            "Match": {
              "Hosts": [ "shadowchats.authentication-unsafe.local" ]
              "Path": "/{**catch-all}"
            }
          }
        ],
        "Clusters": [
          {
            "ClusterId": "authentication"
          }
        ]
      }
    }
