# Shadowchats — Copyright (C) 2025
# Dorovskoy Alexey Vasilievich (One290 / 0ne290) <lenya.dorovskoy@mail.ru>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the LICENSE file for details.
# For full copyright and authorship information, see the COPYRIGHT file.

apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: databases-postgres-pgbouncer-rw
  namespace: databases
spec:
  cluster:
    name: databases-postgres
  instances: 2
  type: rw
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "500"
      default_pool_size: "20"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: databases-postgres-pgbouncer-ro
  namespace: databases
spec:
  cluster:
    name: databases-postgres
  instances: 2
  type: ro
  pgbouncer:
    poolMode: transaction
