apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: DockerHub
        api_url: https://index.docker.io/v1/
        prefix: docker.io
        ping: yes
        credentials: pullSecret:dockerhub-secret

    git:
      write-back-method: git
      commit-message-template: "chore: update image {{ .AppName }} to {{ .ImageTag }}"
      user: ArgoCD Image Updater
      email: image-updater@shadowchats.io
      repos:
        - url: https://github.com/shadowchats/deploy.git
          usernameSecret:
            name: argocd-image-updater-git-creds
            key: username
          passwordSecret:
            name: argocd-image-updater-git-creds
            key: password

    allow-k8s-types: Deployment,Job
