apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
data:
  registries.conf: |
    registries:
      - name: DockerHub
        api_url: https://registry-1.docker.io
        ping: yes
        credentials: pullsecret:argocd/dockerhub-secret
