apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-delegator-global
subjects:
- kind: ServiceAccount
  name: default
  namespace: vault
roleRef:
  kind: ClusterRole
  name: vault-auth-delegator
  apiGroup: rbac.authorization.k8s.io
