apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  vault.hcl: |
    ui = true

    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1 # for minikube/demo only — enable TLS in prod
    }

    storage "raft" {
      path = "/vault/data"
      node_id = "${K8S_POD_NAME}"
    }

    api_addr = "http://vault.vault.svc.cluster.local:8200"
    cluster_addr = "https://vault-internal.vault.svc.cluster.local:8201"
