apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases-postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/shadowchats/deploy.git
    targetRevision: master
    path: databases/postgres
    kustomize: {}
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
