apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/shadowchats/deploy.git
    targetRevision: master
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: shadowchats
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
