apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rbac
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/shadowchats/deploy.git
    targetRevision: HEAD
    path: rbac
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # ClusterRole/ClusterRoleBinding на уровне кластера
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
