# Shadowchats — Copyright (C) 2025
# Dorovskoy Alexey Vasilievich (One290 / 0ne290) <lenya.dorovskoy@mail.ru>
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version. See the LICENSE file for details.
# For full copyright and authorship information, see the COPYRIGHT file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  namespace: shadowchats
spec:
  replicas: 2
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      initContainers:
        - name: vault-agent-init
          image: hashicorp/vault:1.17.6
          args: ["vault", "agent", "-config=/vault/config/vault-agent.hcl"]
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
          volumeMounts:
            - name: vault-config-init
              mountPath: /vault/config
            - name: vault-templates
              mountPath: /vault/templates
            - name: vault-secrets
              mountPath: /vault/secrets
          #resources:
            #requests:
              #cpu: "100m"
              #memory: "128Mi"
            #limits:
              #cpu: "250m"
              #memory: "256Mi"

      containers:
        - name: authentication
          image: one290/shadowchats:authentication-v0.0.0
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          volumeMounts:
            - name: vault-secrets
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          #resources:
            #requests:
              #cpu: "250m"
              #memory: "256Mi"
            #limits:
              #cpu: "1000m"
              #memory: "1Gi"

        - name: vault-agent-sidecar
          image: hashicorp/vault:1.17.6
          args: ["vault", "agent", "-config=/vault/config/vault-agent.hcl"]
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
          volumeMounts:
            - name: vault-config-sidecar
              mountPath: /vault/config
            - name: vault-templates
              mountPath: /vault/templates
            - name: vault-secrets
              mountPath: /vault/secrets
          #resources:
            #requests:
              #cpu: "100m"
              #memory: "128Mi"
            #limits:
              #cpu: "250m"
              #memory: "256Mi"

      volumes:
        - name: vault-config-init
          configMap:
            name: vault-agent-authentication-init

        - name: vault-config-sidecar
          configMap:
            name: vault-agent-authentication-sidecar

        - name: vault-templates
          configMap:
            name: vault-templates-authentication

        - name: vault-secrets
          emptyDir: {}
