apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap-template.yaml
  - vault-agent-config.yaml
  - migrate-job.yaml
  - deployment.yaml
  - hpa.yaml
  - service.yaml

images:
  - name: one290/shadowchats
    newName: one290/shadowchats
    newTag: authentication-v0.0.0
    
patchesStrategicMerge:
  - |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: authentication-migrate
      namespace: shadowchats
    spec:
      template:
        spec:
          containers:
          - name: migrate
            image: one290/shadowchats:authentication-v0.0.0
