apiVersion: batch/v1
kind: Job
metadata:
  name: authentication-migrate
  namespace: shadowchats
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: HookSucceeded,BeforeHookCreation,HookFailed
spec:
  template:
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: vault-agent-init
          image: hashicorp/vault:1.17.6
          args: ["vault", "agent", "-config=/vault/config/vault-agent.hcl"]
          env:
            - name: VAULT_ADDR
              value: "http://vault.vault.svc.cluster.local:8200"
          #resources:
            #requests:
              #cpu: "100m"
              #memory: "128Mi"
            #limits:
              #cpu: "250m"
              #memory: "256Mi"
          volumeMounts:
            - name: vault-config-init
              mountPath: /vault/config
            - name: vault-templates
              mountPath: /vault/templates
            - name: vault-secrets
              mountPath: /vault/secrets

      containers:
        - name: migrate
          image: one290/shadowchats:authentication-v0.0.0
          command: ["dotnet", "Shadowchats.Authentication.Presentation.dll", "migrate"]
          #resources:
            #requests:
              #cpu: "100m"
              #memory: "128Mi"
            #limits:
              #cpu: "250m"
              #memory: "256Mi"
          volumeMounts:
            - name: vault-secrets
              mountPath: /app/appsettings.json
              subPath: appsettings.json

      volumes:
        - name: vault-config-init
          configMap:
            name: vault-agent-authentication-init

        - name: vault-templates
          configMap:
            name: vault-templates-authentication

        - name: vault-secrets
          emptyDir: {}
